theme = "modus_operandi_deuteranopia"

[editor]
color-modes = true
auto-save = true

[editor.cursor-shape]
normal = "block"
select = "block"
insert = "bar"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

