theme = "github_dark"

[editor]
color-modes = true
cursorline = true
auto-save = true
bufferline = "always"

[editor.cursor-shape]
normal = "block"
select = "block"
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
right = ["diagnostics", "selections", "position", "file-type", "file-encoding"]

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

