[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] } 

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] } 

[[language]]
name = "graphql"
formatter = { command = "prettier", args = ["--parser", "graphql"] }

