[language-server.roc-ls]
command = "roc_language_server"

[[language]]
name = "roc"
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
shebangs = ["roc"]
roots = []
comment-token = "#"
language-servers = ["roc-ls", "tailwindcss-ls"]
indent = { tab-width = 2, unit = "  " }
auto-format = true
# formatter = { command = "roc", args = ["format", "--stdin", "--stdout"]}
formatter = { command = "bash", args = ["-c", "roc format --stdin --stdout | rustywind --stdin --custom-regex 'class\\(\"([^\"]+)\"\\)'"]}

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[[grammar]]
name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "0b1afe88161cbd81f5ddea1bb4fa786314ed49a7" }

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { "classFunctions" = ["class"], userLanguages = { roc = "html", "*.roc" = "html" } }

