#! /bin/sh

# Polybar
polybar example &

# bspswallow
pidof bspswallow || bspswallow &

# Notification server
dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI
bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set wallpaper
~/.scripts/setbg ~/media/wallpapers &

# Transparency
picom &

# Fullscreen with transparency fix
cleanfullscreen &

# Set arrow cursor
xsetroot -cursor_name left_ptr &
