# Lines configured by zsh-newuser-install
HISTFILE=~/.cache/zsh/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jisatsu/.config/zsh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

autoload -U colors && colors

PATH=~/.scripts:"$PATH"

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

# Git integration to prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%F{yellow} %b%f '

setopt PROMPT_SUBST
PROMPT='%F{green}[%n]%f %F{blue}%~%f ${vcs_info_msg_0_}%F{green}>%f '
# right side of prompt
RPROMPT='%F{green}<%f'

alias e='exit'
alias c='clear'
alias ll='ls -F -hla --color=auto --group-directories-first'
alias ls='ls -F -hv --color=auto --group-directories-first'


# Allow fzf to user ripgrep
if type rg &> /dev/null; then
    # export FZF_DEFAULT_COMMAND='rg --files'
    export FZF_DEFAULT_COMMAND='rg --files --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
    export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi

# Swap ESC and CAPS buttons
setxkbmap -option caps:swapescape
# Adding US, RU, UA keyboards
setxkbmap -layout us,ru,ua -option grp:alt_shift_toggle

# Load zsh-syntax-highlighting: should be last.
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
